//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ParkingManagementEntities : DbContext
    {
        public ParkingManagementEntities()
            : base("name=ParkingManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spGetCarParkingInfo_Result> spGetCarParkingInfo(Nullable<int> locationInfo)
        {
            var locationInfoParameter = locationInfo.HasValue ?
                new ObjectParameter("LocationInfo", locationInfo) :
                new ObjectParameter("LocationInfo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCarParkingInfo_Result>("spGetCarParkingInfo", locationInfoParameter);
        }
    }
}
